steps:
- task: NodeTool@0
  inputs:
    versionSpec: "16.x"

- script: npm install
  displayName: Install Dependencies

- script: npm test
  displayName: Run Tests

- task: Npm@1
  displayName: 'Publish to NPM'
  inputs:
    command: publish
    verbose: false
    publishEndpoint: 'NPM'
  condition: and(succeeded(), eq(variables['Agent.JobName'], 'Linux'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))