name: CI

on:
  push:
    branches: ['**']
    tags: ['**']
  pull_request:
    branches: ['**']

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            npm_arch: x64
          - os: macos-latest
            npm_arch: arm64
          - os: ubuntu-latest
            npm_arch: x64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install Dependencies
        run: npm install
        env:
          npm_config_arch: ${{ matrix.npm_arch }}

      - name: Run Tests
        run: npm test
