steps:
- task: NodeTool@0
  inputs:
    versionSpec: "16.x"

- script: |
    git submodule update --init
    npm install
  displayName: Install Dependencies

- script: npm test
  displayName: Run Tests
