steps:
- task: NodeTool@0
  inputs:
    versionSpec: "16.x"

- powershell: |
    git submodule update --init
    $env:npm_config_arch="$(NPM_ARCH)"
    npm install
  displayName: Install Dependencies

- script: npm test
  displayName: Run Tests
