trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

jobs:
- job: Windows64
  pool:
    vmImage: 'windows-latest'
  variables:
    NPM_ARCH: 'x64'
  steps:
  - template: build.yml

- job: Windows32
  pool:
    vmImage: 'windows-latest'
  variables:
    NPM_ARCH: 'ia32'
  steps:
  - template: build.yml

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  variables:
    NPM_ARCH: 'x64'
  steps:
  - template: build.yml

- job: Linux
  pool:
    vmImage: 'Ubuntu-latest'
  variables:
    NPM_ARCH: 'x64'
  dependsOn:
  - Windows64
  - Windows32
  - macOS
  steps:
  - template: build.yml
