trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

jobs:
- job: Windows64
  pool:
    vmImage: 'windows-latest'
  variables:
    NPM_ARCH: 'x64'
    OS: 'windows'
  steps:
  - template: build.yml

- job: Windows32
  pool: 1es-windows-2019-x64
  variables:
    NPM_ARCH: 'ia32'
    OS: 'windows'
  steps:
  - template: build.yml

- job: macOS
  pool: macOS-11
  variables:
    NPM_ARCH: 'x64'
    OS: 'macOS'
  steps:
  - template: build.yml

- job: Linux
  pool: 1es-oss-ubuntu-20.04-x64
  variables:
    NPM_ARCH: 'x64'
    OS: 'Linux'
  dependsOn:
  - Windows64
  - Windows32
  - macOS
  steps:
  - template: build.yml
