trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: build.yml

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: build.yml

- job: Linux
  pool:
    vmImage: 'Ubuntu-latest'
  dependsOn:
  - Windows
  - macOS
  steps:
  - template: build.yml
