name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishPackage
    displayName: 🚀 Publish node-spdlog
    type: boolean
    default: false

extends:
  template: azure-pipelines/npm-package/pipeline.yml@templates
  parameters:
    npmPackages:
      - name: node-spdlog

        buildSteps:
          - script: |
              git submodule update --init
              npm ci
            displayName: Install dependencies

        testPlatforms:
          - name: Linux
            nodeVersions:
              - 18.17.x
          - name: MacOS
            nodeVersions:
              - 18.17.x
          - name: Windows
            nodeVersions:
              - 18.17.x

        testSteps:
          - script: |
              git submodule update --init
              npm ci
            displayName: Install dependencies

          - script: |
              make --version
              g++ --version
              clang --version
            displayName: Check tool versions (non-Windows)
            condition: not(contains(variables['Agent.OS'], 'windows'))

          - pwsh: |
              & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe --version"
              & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\CL.exe"
              & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe"
            displayName: Check tool versions (Windows)
            condition: contains(variables['Agent.OS'], 'windows')

          - script: npm run test
            displayName: Compile & test npm package

        publishPackage: ${{ parameters.publishPackage }}